// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_a1gQuI6qzgJ0C34e5fppm3BoRiULx4A',
    appId: '1:842835616405:web:7b3f52d7befd6fe844719c',
    messagingSenderId: '842835616405',
    projectId: 'nourish-ninja-72d39',
    authDomain: 'nourish-ninja-72d39.firebaseapp.com',
    storageBucket: 'nourish-ninja-72d39.appspot.com',
    measurementId: 'G-ME8L502LEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0jQemecyaKlDaKD1cQ7h0EhxVrCMDAY',
    appId: '1:842835616405:android:f00fe2a12840867344719c',
    messagingSenderId: '842835616405',
    projectId: 'nourish-ninja-72d39',
    storageBucket: 'nourish-ninja-72d39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOyJkkBiPWPrI-42LSlsZyedDP3S5h5Y8',
    appId: '1:842835616405:ios:d1521041a95ab67444719c',
    messagingSenderId: '842835616405',
    projectId: 'nourish-ninja-72d39',
    storageBucket: 'nourish-ninja-72d39.appspot.com',
    iosClientId: '842835616405-5007teql95juk7bqpi635hpjane1vdor.apps.googleusercontent.com',
    iosBundleId: 'com.example.nourishNinja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOyJkkBiPWPrI-42LSlsZyedDP3S5h5Y8',
    appId: '1:842835616405:ios:d7014563ef03fffe44719c',
    messagingSenderId: '842835616405',
    projectId: 'nourish-ninja-72d39',
    storageBucket: 'nourish-ninja-72d39.appspot.com',
    iosClientId: '842835616405-bk31dpue7gmmkpkfvh4ttejmjntfl6ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.nourishNinja.RunnerTests',
  );
}
